# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/suzano_inspection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

spring.main.allow-circular-references=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativa H2
spring.h2.console.enabled=false

# AWS (desativado em dev)
aws.s3.bucket-name=local-dev-bucket
aws.s3.region=us-east-1
aws.access-key-id=
aws.secret-access-key=


